---

# Rails fixes from https://github.com/troessner/reek/blob/master/README.md#working-with-rails
"app/controllers":
  IrresponsibleModule:
    enabled: false
  NestedIterators:
    max_allowed_nesting: 2
  UnusedPrivateMethod:
    enabled: false
  InstanceVariableAssumption:
    enabled: false
"app/helpers":
  IrresponsibleModule:
    enabled: false
  UtilityFunction:
    enabled: false
"app/mailers":
  InstanceVariableAssumption:
    enabled: false
"app/models":
   IrresponsibleModule:
     enabled: false
"app/queries":
   IrresponsibleModule:
     enabled: false

DuplicateMethodCall:
  max_calls: 2

UtilityFunction:
  public_methods_only: true

ControlParameter:
  exclude:
  - initialize

exclude_paths:
  - db/migrate/
  - spec/support/
